CinemaPOS/Models/Actividades.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaPOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Actividades
    {
        public int rowID { get; set; }
        public string asunto { get; set; }
        public int tipoActividadID { get; set; }
        public System.DateTime fechaInicio { get; set; }
        public Nullable<System.DateTime> fechaFin { get; set; }
        public int tipoReferenciaID { get; set; }
        public string referenciado_a { get; set; }
        public int prioridadID { get; set; }
        public int estadoID { get; set; }
        public string descripcion { get; set; }
        public System.DateTime fechaCreacion { get; set; }
        public string creadoPor { get; set; }
        public Nullable<System.DateTime> fechaMod { get; set; }
        public string usuarioMod { get; set; }
    
        public virtual Estado Estado { get; set; }
        public virtual Opcion Opcion { get; set; }
        public virtual Opcion Opcion1 { get; set; }
        public virtual Opcion Opcion2 { get; set; }
    }
}

CinemaPOS/Models/ClienteRoyal.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaPOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClienteRoyal
    {
        public ClienteRoyal()
        {
            this.TarjetaMembresiaClienteRoyal = new HashSet<TarjetaMembresiaClienteRoyal>();
        }
    
        public int RowID { get; set; }
        public string Documento { get; set; }
        public string CorreoElectronico { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public string Telefono { get; set; }
        public Nullable<bool> RecibirInformacion { get; set; }
        public Nullable<System.DateTime> FechaNacimiento { get; set; }
        public Nullable<int> CiudadResidenciaID { get; set; }
        public Nullable<int> GeneroID { get; set; }
        public Nullable<int> ClasificacionID { get; set; }
        public string CreadoPor { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string UsuarioMod { get; set; }
        public Nullable<System.DateTime> FechaMod { get; set; }
        public Nullable<int> preferenciasID { get; set; }
    
        public virtual Ciudad Ciudad { get; set; }
        public virtual Opcion Opcion { get; set; }
        public virtual Opcion Opcion1 { get; set; }
        public virtual ICollection<TarjetaMembresiaClienteRoyal> TarjetaMembresiaClienteRoyal { get; set; }
        public virtual Opcion Opcion2 { get; set; }
    }
}

CinemaPOS/Controllers/CRMController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CinemaPOS.Models;
using CinemaPOS.ModelosPropios;
namespace CinemaPOS.Controllers
{
    public class CRMController : Controller
    {
        CinemaPOSEntities db = new CinemaPOSEntities();
        //
        // GET: /CRM/
        private FormCollection DeSerialize(FormCollection formulario)
        {
            FormCollection collection = new FormCollection();
            //un-encode, and add spaces back in
            string querystring = Uri.UnescapeDataString(formulario["formulario"]).Replace("+", " ");
            var split = querystring.Split(new[] { '&' }, StringSplitOptions.RemoveEmptyEntries);
            Dictionary<string, string> items = new Dictionary<string, string>();
            foreach (string s in split)
            {
                string text = s.Substring(0, s.IndexOf("="));
                string value = s.Substring(s.IndexOf("=") + 1);

                if (items.Keys.Contains(text))
                    items[text] = items[text] + "," + value;
                else
                    items.Add(text, value);
            }
            foreach (var i in items)
            {
                collection.Add(i.Key, i.Value);
            }
            return collection;
        }
        public ActionResult RegistroClienteTarjeta()
        {
            ViewBag.Ciudades = db.Ciudad.ToList();
            ViewBag.Generos = db.Opcion.Where(g => g.Tipo.Codigo == "TIPOSEXO").ToList();
            ViewBag.TipoCliente = db.Opcion.Where(g => g.Tipo.Codigo == "TIPOCLIENTE").ToList();
            return View();
        }
        public JsonResult GuardarCliente(FormCollection formulario)
        {
            formulario = DeSerialize(formulario);
            ClienteRoyal obj_cliente =new  ClienteRoyal();
            obj_cliente.Apellido = formulario["apellidos"];
            obj_cliente.Nombre = formulario["nombres"];
            obj_cliente.Documento = formulario["identificacion"];
            obj_cliente.CorreoElectronico = formulario["ciudad"];
            obj_cliente.Telefono = formulario["telefono"];
            obj_cliente.CiudadResidenciaID = int.Parse(formulario["ciudad"].ToString());
            obj_cliente.GeneroID = int.Parse(formulario["genero"]);
            obj_cliente.FechaNacimiento = ModelosPropios.Util.HoraInsertar(formulario["fecha_nacimiento"]);
            obj_cliente.ClasificacionID = int.Parse(formulario["clasificacion"]);
            obj_cliente.CiudadResidenciaID = int.Parse(formulario["nombre"]);
            db.ClienteRoyal.Add(obj_cliente);
            db.SaveChanges();
            return  Json("asd");
        }

        #region CRM CLIENTE ROYAL
        [CheckSessionOutAttribute]
        public ActionResult ClienteRoyal(int? rowid)
        {
            List<Util.ClientesRoyal> cliente = new List<Util.ClientesRoyal>();
            cliente = (from clientes in db.ClienteRoyal
                       join tarjetaM in db.TarjetaMembresiaClienteRoyal
                       on clientes.RowID equals tarjetaM.ClienteRoyalID
                       join membresia in db.TarjetaMembresia
                       on tarjetaM.TarjetaMembresiaID equals membresia.RowID
                        select new ModelosPropios.Util.ClientesRoyal
                        {
                            rowid = clientes.RowID,
                            documento = clientes.Documento,
                            correo = clientes.CorreoElectronico,
                            nombreCompleto = clientes.Nombre + " " + clientes.Apellido,
                            telefono = clientes.Telefono,
                            ciudades = (clientes.CiudadResidenciaID == null) ? "" : clientes.Ciudad.Nombre + " " + clientes.Ciudad.Departamento.Nombre,
                            genero = (clientes.GeneroID == null) ? "" : db.Opcion.Where(f=>f.RowID==clientes.GeneroID).FirstOrDefault().Nombre,
                            fechaNac = clientes.FechaNacimiento,
                            tarjetaID = (membresia.Codigo==null)? "": membresia.Codigo,
                            info = clientes.RecibirInformacion,
                            clasificacion = (clientes.Opcion == null) ? "" : db.Opcion.Where(f => f.RowID == clientes.ClasificacionID).FirstOrDefault().Nombre,
                            pref = (clientes.preferenciasID == null) ? "" : db.Opcion.Where(f => f.RowID == clientes.preferenciasID).FirstOrDefault().Nombre
                        }).ToList();
            ViewBag.Listado = cliente;
            return View();
        }

        [CheckSessionOutAttribute]
        public ActionResult NuevoClienteRoyal(int? rowID)
        {
            ViewBag.TipoIdentificacion = db.Opcion.Where(f => f.Tipo.Codigo == "TIPOIDENTIFICACION").ToList();
            ViewBag.Ciudades = db.Ciudad.ToList();
            ViewBag.SexoID = db.Opcion.Where(f => f.Tipo.Codigo == "TIPOSEXO").ToList();
            ViewBag.Clasificacion = db.Opcion.Where(f => f.Tipo.Codigo == "TIPOCLIENTE").ToList();
            ViewBag.preferencias = db.Opcion.Where(f => f.Tipo.Codigo == "TIPOGENEROPELICULA").ToList();
            TarjetaMembresiaClienteRoyal tmembresia = new TarjetaMembresiaClienteRoyal();
            try
            {tmembresia = db.TarjetaMembresiaClienteRoyal.Where(f => f.ClienteRoyalID == rowID).FirstOrDefault();}
            catch{}
            TarjetaMembresia membresia = new TarjetaMembresia();
            try
            {membresia = db.TarjetaMembresia.Where(f => f.RowID == tmembresia.TarjetaMembresiaID).FirstOrDefault();}
            catch{}
            ViewBag.Tarjeta = membresia.Codigo;
            ClienteRoyal royal = db.ClienteRoyal.Where(f => f.RowID == rowID).FirstOrDefault();
            if (royal == null)
                royal = new Models.ClienteRoyal();

            return View(royal);
        }

        [CheckSessionOutAttribute]
        [HttpPost]
        public JsonResult GuardarClienteRoyal(int? rowID, FormCollection formulario)
        {
            formulario = DeSerialize(formulario);
            ClienteRoyal cliente = db.ClienteRoyal.Where(f => f.RowID == rowID).FirstOrDefault();
            if (cliente == null || rowID == 0)
            {cliente = new Models.ClienteRoyal();}

            try
            {
                cliente.Apellido = formulario["Apellido"];
                cliente.Nombre = formulario["Nombre"];
                cliente.Documento = formulario["Documento"];
                cliente.CorreoElectronico = formulario["CorreoElectronico"];
                cliente.Telefono = formulario["Telefono"];
                string info = formulario["RecibirInformacion"];
                if (info == "on")
                { cliente.RecibirInformacion = true; }
                else { cliente.RecibirInformacion = false; }
                cliente.FechaNacimiento = ModelosPropios.Util.HoraInsertar(formulario["FechaNacimiento"]);
                cliente.CiudadResidenciaID = Convert.ToInt32(formulario["CiudadResidenciaID"]);
                cliente.GeneroID = Convert.ToInt32(formulario["GeneroID"]);
                cliente.ClasificacionID = Convert.ToInt32(formulario["ClasificacionID"]);
                cliente.preferenciasID = Convert.ToInt32(formulario["preferenciasID"]);
                cliente.CreadoPor = Session["usuario_creacion"].ToString();
                cliente.FechaNacimiento = DateTime.Now;
                string cofd = formulario["TarjetaMembresiaClienteRoyal"].ToString();
                TarjetaMembresia membresia = db.TarjetaMembresia.Where(f => f.Codigo == cofd).FirstOrDefault();
                if (membresia == null)
                {membresia = new TarjetaMembresia();}
                string codigo = formulario["TarjetaMembresiaClienteRoyal"];
                membresia.Codigo = codigo;
                membresia.CreadoPor = Session["usuario_creacion"].ToString();
                membresia.FechaCreacion = DateTime.Now;
                membresia.EstadoID = Util.Constantes.ESTADO_ACTIVO;
                membresia.NoRedenciones = Util.Constantes.REDENCIONES_No4;
                if (membresia == null || rowID == 0)
                {db.TarjetaMembresia.Add(membresia);}
                db.SaveChanges();
                if (rowID == null || rowID == 0)
                {db.ClienteRoyal.Add(cliente);}
                db.SaveChanges();

                TarjetaMembresiaClienteRoyal tarjetaID = db.TarjetaMembresiaClienteRoyal.Where(f => f.ClienteRoyalID == rowID).FirstOrDefault();
                if (tarjetaID == null || rowID == 0)
                { tarjetaID = new TarjetaMembresiaClienteRoyal(); }
                tarjetaID.TarjetaMembresiaID = membresia.RowID;
                tarjetaID.ClienteRoyalID = cliente.RowID;
                tarjetaID.FechaActivacion = DateTime.Now;
                tarjetaID.EstadoID = Util.Constantes.ESTADO_ACTIVO;
                tarjetaID.NoRedencionesAprob = Util.Constantes.REDENCIONES_No4;
                if (rowID == null || rowID == 0)
                {db.TarjetaMembresiaClienteRoyal.Add(tarjetaID);}
                db.SaveChanges();
                return Json(new { respuesta = "ok", clienteRoyal = cliente.RowID });
            }
            catch (Exception e)
            {
                return Json("error" + e);
            }
        }
        #endregion

        #region CRM COTIZACIONES
        [CheckSessionOutAttribute]
        public ActionResult ListadoCotizaciones(int? rowid)
        {
            List<Util.Cotizaciones> cotizaciones = new List<Util.Cotizaciones>();

            cotizaciones = (from cotizacion in db.OportunidadVenta
                            join tercero in db.Tercero
                            on cotizacion.ProspectoID equals tercero.RowID
                            join teatros in db.Teatro
                            on cotizacion.TeatroID equals teatros.RowID
                            join lista in db.ListaEncabezado

CinemaPOS/Views/CRM/ClienteRoyal.cshtml
@model CinemaPOS.ModelosPropios.Util.ClientesRoyal
@{
    ViewBag.Title = "ClienteRoyal";
    Layout = "~/Views/Inicio/Diseño.cshtml";
}

<!--jQuery [ REQUIRED ]-->
<script src="~/Content/js/jquery-2.2.4.min.js"></script>
<!--DataTables [ OPTIONAL ]-->
<script src="~/Content/plugins/datatables/media/js/jquery.dataTables.js"></script>
<script src="~/Content/plugins/datatables/media/js/dataTables.bootstrap.js"></script>
<script src="~/Content/plugins/datatables/extensions/Responsive/js/dataTables.responsive.min.js"></script>
<!--DataTables Sample [ SAMPLE ]-->
<script src="~/Content/js/demo/tables-datatables.js"></script>
@*<script src="~/Content/js/JqueryDataRables/jquery.dataTables.min.js"></script>
<link href="~/Content/Tables.min.css" rel="stylesheet" />
<link href="~/Content/css/JqueryDataTables/jquery.dataTables.min.css" rel="stylesheet" />*@
<p>
    <a class="btn btn-success" href='@Url.Action("NuevoClienteRoyal", "CRM")'>Crear Cliente Royal</a>
</p>

<div class="panel">
    <div class="panel-heading">
        <h3 class="panel-title">Lista Terceros</h3>
    </div>
    <div class="panel-body">
        <table id="demo-dt-basic" class="table table-striped table-bordered table-hover" cellspacing="0" style="width:100%">
            <thead>
                <tr>
                    <th>Nombre Completo</th>
                    <th>Documento</th>
                    <th>Correo</th>
                    <th>Tel&eacute;fono</th>
                    <th>Ciudad</th>
                    <th>Tarjeta ID</th>
                    <th>Clasificaci&oacute;n</th>
                    <th>Preferencias</th>
                    <th></th>
                </tr>
            </thead>
            @*<tfoot>
                <tr>
                    <th>ID</th>
                    <th>Nombre Completo</th>
                    <th>Documento</th>
                    <th>Correo</th>
                    <th>Telefono</th>
                    <th>Ciudad</th>
                    <th>Tarjeta ID</th>
                    <th>Clasificacion</th>
                    <th>Preferencias</th>
                    <th></th>
                </tr>
            </tfoot>*@
            <tbody>
                @foreach (var item in (List<CinemaPOS.ModelosPropios.Util.ClientesRoyal>)ViewBag.Listado)
                {
                    <tr>
                        <td>@item.nombreCompleto</td>
                        <td>@item.documento</td>
                        <td>@item.correo</td>
                        <td>@item.telefono</td>
                        <td>@item.ciudades</td>
                        <td>@item.tarjetaID</td>
                        <td>@item.clasificacion</td>
                        <td>@item.pref</td>
                        <td><a href="@Url.Action("NuevoClienteRoyal", "CRM", new { @rowid = item.rowid })"><i class="glyphicon glyphicon-pencil"></i></a></td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>
@*<script>
    $(document).ready(function () { 
    var cont = 0;
    $('#demo-dt-basic tfoot th').each(function () {
        var title = $(this).text();
        var width = 'width: 100px;';
        var id = '';

        if (title == 'ID')
            id = 'id="ID"';

        if (title == 'Nombre Completo')
            id = ' id="Nombre_Completo"';

        if (title == 'Documento')
            id = 'id="Documento"';

        if (title == 'Telefono')
            id = 'id="Telefono"';

        if (title == 'Ciudad')
            id = 'id="Ciudad"';

        if (title == 'Tarjeta ID')
            id = 'id="Tarjeta_ID"';

        if (title == 'Clasificacion')
            id = 'id="Clasificacion"';

        if (title == 'Preferencias')
            id = 'id="Preferencias"';
        if (title != '')
            $(this).html('<input type="text" style="' + width + '" ' + id + ' placeholder="Buscar ' + title + '" />');
        else
            title = '';
        cont += 1;
    });
    var aoColumnDefsType = [
       //{ "sType": "title-numeric", "aTargets": [3] },
       //{ "sType": "title-numeric", "aTargets": [7] },
       { "bSortable": false, "aTargets": [0] }//,
       //{ "bSortable": false, "aTargets": [8] },
       //{ "bSortable": false, "aTargets": [9] },
       //{ "sClass": "center", "aTargets": [2, 3, 4, 5, 6, 7] }
    ];

    var table = $('#demo-dt-basic').DataTable({
        "processing": true,
        "bFilter": true,
        "bPaginate": true,
        "info": true,
        "bDestroy": true,        
        aLengthMenu: [
            [6],
            [6]
        ],
        "iDisplayLength": 6, 
        "order": [[2, "desc"]],
        "aoColumnDefs":aoColumnDefsType
        //"aaSorting": [[2,'desc']]   
    });

        // Apply the search
    table.columns().every(function () {
        var that = this;

        $('input', this.footer()).on('keyup change', function () {
            if (that.search() !== this.value) {
                that
                    .search(this.value)
                    .draw();
            }
        });
    });
    });
</script>*@

CinemaPOS/Views/CRM/Cotizaciones.cshtml
@model CinemaPOS.Models.OportunidadVenta
@{
    ViewBag.Title = "Cotizaciones";
    Layout = "~/Views/Inicio/Diseño.cshtml";
}
<p>
    <a class="btn btn-success" href='@Url.Action("ListadoCotizaciones", "CRM")'>Vista</a>
</p>
<div id="content"></div>
<div class="panel">
    <div class="panel-heading">
        <h3 class="panel-title">Oportunidad de Venta</h3>
    </div>
    <form name="form_cotizacion" id="form_cotizacion" onsubmit="return false">
        <input type="hidden" id="rowID" value="@Model.RowID" name="rowID" />
        <div class="panel-body">
            <div class="row">
                <div class="col-sm-4">
                    <div class="form-group">
                        <label for="TITULO">T&iacute;tulo</label>
                        <input type="text" name="Titulo" value="@Model.Titulo" id="Titulo" class="form-control" required/>
                    </div>
                </div>
                <div class="col-sm-4">
                    <div class="form-group">
                        <label for="PROSPECTO">*Prospecto:</label>
                        <select name="ProspectoIDx" id="ProspectoIDx" required>
                            <option value="" selected>Seleccione una Opci&oacute;n</option>
                            @foreach (var item in (List<CinemaPOS.Models.Tercero>)ViewBag.prospectos)
                            {
                                if (Model.ProspectoID == item.RowID)
                                {<option value="@item.RowID" selected>@item.Nombre - @item.Apellidos</option>}
                                else
                                {<option value="@item.RowID">@item.Nombre - @item.Apellidos</option>}
                            }
                        </select>
                    </div>
                </div>
            </div>
            <div class="row">

                <div class="col-sm-4">
                    <div class="form-group">
                        <label for="TEATRO">*Sucursal:</label>
                        <select name="TeatroID" id="TeatroID" required>
                            <option value="" selected>Seleccione una Opci&oacute;n</option>
                            @foreach (var item in (List<CinemaPOS.Models.Teatro>)ViewBag.teatros)
                            {
                                if (Model.TeatroID == item.RowID)
                                {<option value="@item.RowID" selected>@item.Nombre</option>}
                                else
                                {<option value="@item.RowID">@item.Nombre</option>}
                            }
                        </select>
                    </div>
                </div>
                <div class="col-sm-4">
                    <div class="form-group">
                        <label for="CONTACTO">Nombre Contacto:</label>
                        <input type="text" name="contactoID" value="" id="contactoID" class="form-control" readonly="readonly"/>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-4">
                    <div class="form-group">
                        <label for="ESTADOS">*Estado:</label>
                        <select name="estadoID" id="estadoID" required>
                            <option value="">Seleccione una Opci&oacute;n</option>
                            @foreach (var item in (List<CinemaPOS.Models.Estado>)ViewBag.estado)
                            {
                                if (Model.EstadoID == item.RowID)
                                {
                            <option value="@item.RowID" selected>@item.Nombre</option>}
                                else
                                {
                            <option value="@item.RowID">@item.Nombre</option>}
                            }
                        </select>
                    </div>
                </div>
                <div class="col-sm-4">
                    <div class="form-group">
                        <label for="CELULAR">Celular Contacto:</label>
                        <input type="text" name="celular" value="" id="celular" class="form-control" readonly="readonly"/>
                        <input type="hidden" name="ContactoHiden" value="" id="ContactoHiden" />
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-4">
                    <div class="form-group">
                        <label for="VALOR">*Valor:</label>
                        <input type="text" name="Valor" value="@Model.Valor" id="Valor" class="form-control" required style="width:100%"/>
                    </div>
                </div>
                <div class="col-sm-4">
                    <div class="form-group">
                        <label for="FECHAAPERTURA">*Fecha Apertura:</label>
                        <input type="text" name="FechaApertura" value="@Model.FechaApertura" id="FechaApertura" class="form-control"/>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-4">
                    <div class="form-group">
                        <label for="LISTAPRECIOS">*Lista Precios:</label>
                        <select name="ListaPrecioID" id="ListaPrecioID" class="form-control">
                            <option value="">Seleccione un Opci&oacute;n</option>
                            @foreach (var item in (List<CinemaPOS.Models.ListaEncabezado>)ViewBag.ListaPrecios)
                            {
                                if (Model.ListaPrecioID == item.RowID)
                                {<option value="@item.RowID" selected>@item.Nombre</option>}
                                else
                                {<option value="@item.RowID">@item.Nombre</option>}
                            }
                        </select>
                    </div>
                </div>
                <div class="col-sm-4">
                    <div class="form-group">
                        <label for="FECHAENTREGA">*Fecha Entrega:</label>
                        <input type="text" name="FechaEntrega" value="@Model.FechaEntrega" id="FechaEntrega" class="form-control" />
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-4">
                    <div class="form-group">
                        <label for="DESCRIPCION">Descripci&oacute;n:</label>
                        <textarea name="Descripcion" id="Descripcion" class="form-control" placeholder="---">@Model.Descripcion</textarea>
                    </div>
                </div>
                <div class="col-sm-4">
                    <div class="form-group">
                        <label for="FECHACIERRE">*Fecha Cirre:</label>
                        <input type="text" name="FechaCierra" value="@Model.FechaCierra" id="FechaCierra" class="form-control" />
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-4">
                    <div class="form-group">
                        <a onclick="javascript:GuardarCotizacion();" class="btn btn-success" style="cursor:pointer">Guardar Cotizaci&oacute;n</a>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>
<script>
    $(document).ready(function () {
        jQuery("#ProspectoIDx").chosen({ width: "100%;" });
        jQuery("#TeatroID").chosen({ width: "100%;" });
        jQuery("#estadoID").chosen({ width: "100%;" });
        jQuery("#ListaPrecioID").chosen({ width: "98%;" });
        jQuery.validator.messages.required = 'Este campo es obligatorio.';
        jQuery.validator.messages.mail = 'Ingrese un correo valido.';
        $.validator.setDefaults({ ignore: ":hidden:not(select)" });
    });
    $(document).ready(function () {
        ModalProcesandoShow();
        if ($("#ProspectoIDx") != "") {
            $.ajax({
                type: "POST",
                url: "/CRM/ContactoAsignado",
                data: {
                    ProspectoID: $("#ProspectoIDx").val(),
                },
                success: function (data) {
                    debugger
                    ModalProcesandoHiden();
                    $("#contactoID").val(data.nombreContacto);
                    $("#ContactoHiden").val(data.rowidContacto);
                    $("#celular").val(data.celular);
                    $("#contactoID").attr("disabled", true);
                    $("#celular").attr("disabled", true);
                },
                error: function (data) {
                    ModalProcesandoHiden();
                }
            });
        }
    });
    $("#ProspectoIDx").change(function () {
        ModalProcesandoShow();
        $.ajax({
            type: "POST",
            url: "/CRM/ContactoAsignado",
            data: {
                ProspectoID: $("#ProspectoIDx").val(),
            },
            success: function (data) {
                debugger
                ModalProcesandoHiden();
                $("#contactoID").val(data.nombreContacto);
                $("#ContactoHiden").val(data.rowidContacto);
                $("#celular").val(data.celular);
                $("#contactoID").attr("disabled", true);
                $("#celular").attr("disabled", true);
            },
            error: function (data) {
                ModalProcesandoHiden();
            }
        });
    });
    $('#FechaEntrega').datepicker({
        format: "dd/MM/yyyy",
        todayBtn: "linked",
        autoclose: true,
        todayHighlight: false
    });
    $('#FechaApertura').datepicker({
        format: "dd/MM/yyyy",
        todayBtn: "linked",
        autoclose: true,
        todayHighlight: false
    });
    $('#FechaCierra').datepicker({
        format: "dd/MM/yyyy",
        todayBtn: "linked",
        autoclose: true,
        todayHighlight: false
    });
</script>

<!--GUARDAR COTIZACIÓN-->
<script>
    function GuardarCotizacion() {
        debugger
        ModalProcesandoShow();
        $.ajax({
            type: "POST",
            url: "/CRM/GuardarCotizacion",
            data: {
                rowID: $("#RowID").val(),
                formulario: $("#form_cotizacion").serialize(),
            },
            success: function (data) {
                
                ModalProcesandoHiden();
                if (data.respuesta == "ok") {
                    swal("Datos almecenados correctamente.", "", "success");
                    window.location = "/CRM/ListadoCotizaciones"
                    return;
                } else {
                    ModalProcesandoHiden();
                    swal("ERROR", data.respuesta, "error");
                }

            },
            error: function (data) {
                ModalProcesandoHiden();
                swal("ERROR", data.respuesta, "error");
            }
        });
    }
</script>

CinemaPOS/Views/CRM/ListadoActividades.cshtml
@model CinemaPOS.ModelosPropios.Util.Actividades
@{
    ViewBag.Title = "ListadoActividades";
    Layout = "~/Views/Inicio/Diseño.cshtml";
}
<p>
    <a class="btn btn-success" href='@Url.Action("Actividades", "CRM")'>Crear Actividad</a>
</p>

<div class="panel">
    <div class="panel-heading">
        <h3 class="panel-title">Lista Terceros</h3>
    </div>
    <div class="panel-body">
        <table id="demo-dt-basic" class="table table-striped table-bordered table-hover" cellspacing="0" style="width:100%">
            <thead>
                <tr>
                    <th>Tipo</th>
                    <th>Asunto</th>
                    <th>Prioridad</th>
                    <th>Referenciado a</th>
                    <th>Descripci&oacute;n</th>
                    <th>Inicio</th>
                    <th>Fin</th>
                    <th>Estado</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in (List<CinemaPOS.ModelosPropios.Util.Actividades>)ViewBag.Listado)
                {
                    <tr>
                        <td>@item.tipoAct</td>
                        <td>@item.asunto</td>
                        <td>@item.prioridad</td>
                        <td>@item.referenciado_a</td>
                        <td>@item.descripcion</td>
                        <td>@item.fechaInicio</td>
                        <td>@item.FechaFin</td>
                        <td>@item.estado</td>
                        <td><a href="@Url.Action("Actividades", "CRM", new { @rowid = item.rowid })"><i class="glyphicon glyphicon-pencil"></i></a></td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>