CinemaPOS/Models/Ciudad.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaPOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ciudad
    {
        public Ciudad()
        {
            this.ClienteRoyal = new HashSet<ClienteRoyal>();
            this.Teatro = new HashSet<Teatro>();
            this.Tercero = new HashSet<Tercero>();
        }
    
        public int RowID { get; set; }
        public int DepartamentoID { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
    
        public virtual ICollection<ClienteRoyal> ClienteRoyal { get; set; }
        public virtual Departamento Departamento { get; set; }
        public virtual ICollection<Teatro> Teatro { get; set; }
        public virtual ICollection<Tercero> Tercero { get; set; }
    }
}

CinemaPOS/Models/Departamento.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaPOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Departamento
    {
        public Departamento()
        {
            this.Ciudad = new HashSet<Ciudad>();
        }
    
        public int RowID { get; set; }
        public int PaisID { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
    
        public virtual ICollection<Ciudad> Ciudad { get; set; }
        public virtual Pais Pais { get; set; }
    }
}

CinemaPOS/Models/MapaSala.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaPOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MapaSala
    {
        public MapaSala()
        {
            this.BoletaVendida = new HashSet<BoletaVendida>();
        }
    
        public int RowID { get; set; }
        public Nullable<int> ObjetoID { get; set; }
        public Nullable<int> ZonaID { get; set; }
        public Nullable<int> SalaID { get; set; }
        public Nullable<int> EstadoID { get; set; }
        public string Columna { get; set; }
        public Nullable<short> Fila { get; set; }
        public Nullable<short> PosicionX { get; set; }
        public Nullable<short> PosicionY { get; set; }
        public string CreadoPor { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public string ModificadoPor { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public Nullable<bool> Sincronizado { get; set; }
    
        public virtual Estado Estado { get; set; }
        public virtual SalaObjeto SalaObjeto { get; set; }
        public virtual Zona Zona { get; set; }
        public virtual ICollection<BoletaVendida> BoletaVendida { get; set; }
        public virtual Sala Sala { get; set; }
    }
}

CinemaPOS/Models/Menu.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaPOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu
    {
        public Menu()
        {
            this.RolMenu = new HashSet<RolMenu>();
        }
    
        public int RowID { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public string URL { get; set; }
        public int TipoMenuID { get; set; }
        public string Imagen { get; set; }
        public bool Activo { get; set; }
        public string CreadoPor { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string ModificadoPor { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public Nullable<bool> Sincronizado { get; set; }
    
        public virtual Tipo Tipo { get; set; }
        public virtual Tipo Tipo1 { get; set; }
        public virtual TipoMenu TipoMenu { get; set; }
        public virtual ICollection<RolMenu> RolMenu { get; set; }
    }
}

CinemaPOS/Models/Pais.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaPOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pais
    {
        public Pais()
        {
            this.Departamento = new HashSet<Departamento>();
            this.EncabezadoPelicula = new HashSet<EncabezadoPelicula>();
        }
    
        public int RowID { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
    
        public virtual ICollection<Departamento> Departamento { get; set; }
        public virtual ICollection<EncabezadoPelicula> EncabezadoPelicula { get; set; }
    }
}

CinemaPOS/Models/Zona.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaPOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zona
    {
        public Zona()
        {
            this.MapaSala = new HashSet<MapaSala>();
        }
    
        public int RowID { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> Prioridad { get; set; }
        public string CreadoPor { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string ModificadoPor { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public Nullable<bool> Sincronizado { get; set; }
    
        public virtual ICollection<MapaSala> MapaSala { get; set; }
    }
}

CinemaPOS/Controllers/MaestroController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CinemaPOS.Models;
using System.IO;
using System.Data.Entity;
using System.Net;
using System.Data;

namespace CinemaPOS.Controllers.Master
{
    public class MaestroController : Controller
    {
        ModelosPropios.Util lol = new ModelosPropios.Util();
        CinemaPOSEntities db = new CinemaPOSEntities();

        #region General
        private FormCollection DeSerialize(FormCollection formulario)
        {
            FormCollection collection = new FormCollection();
            //un-encode, and add spaces back in
            string querystring = Uri.UnescapeDataString(formulario["formulario"]).Replace("+", " ");
            var split = querystring.Split(new[] { '&' }, StringSplitOptions.RemoveEmptyEntries);
            Dictionary<string, string> items = new Dictionary<string, string>();
            foreach (string s in split)
            {
                string text = s.Substring(0, s.IndexOf("="));
                string value = s.Substring(s.IndexOf("=") + 1);

                if (items.Keys.Contains(text))
                    items[text] = items[text] + "," + value;
                else
                    items.Add(text, value);
            }
            foreach (var i in items)
            {
                collection.Add(i.Key, i.Value);
            }
            return collection;
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        #endregion

        #region Precio
        [CheckSessionOutAttribute]
        public ActionResult Precio(int? RowID_Lista)
        {
            ViewBag.Teatros = db.Teatro.ToList();
            ViewBag.Servicios = db.Opcion.Where(s => s.Tipo.Codigo == "TIPOSERVICIO").ToList();
            ViewBag.Formatos = db.Opcion.Where(f => f.Tipo.Codigo == "TIPOFORMATO").ToList();
            ViewBag.TipoTarifa = db.Opcion.Where(f => f.Tipo.Codigo == "TIPOLISTADETALLE").ToList();
            ViewBag.ListaEstados = db.Estado.Where(f => f.TipoEstado.Codigo == "TIPOLISTAPRECIO").ToList();
            if (RowID_Lista != null)
            {
                return View(db.ListaEncabezado.Where(le => le.RowID == RowID_Lista).FirstOrDefault());
            }
            else
            {
                return View(new ListaEncabezado());
            }
        }
        [CheckSessionOutAttribute]
        public ActionResult VistaPrecio()
        {
            ViewBag.ListasPrecio = db.ListaEncabezado.ToList();

            return View();
        }

        //public ActionResult Precio(int? rowid)
        //{
        //    ListaEncabezado encabezado = db.ListaEncabezado.Where(f => f.RowID == rowid).FirstOrDefault();
        //    ViewBag.Teatros = db.Teatro.ToList();
        //    ViewBag.Servicios = db.Opcion.Where(s => s.Tipo.Codigo == "TIPOSERVICIO").ToList();
        //    ViewBag.Formatos = db.Opcion.Where(f => f.Tipo.Codigo == "TIPOFORMATO").ToList();
        //    return View(encabezado);
        //}
        [CheckSessionOutAttribute]
        public JsonResult Guardar_Lista_Precio(FormCollection formulario, int? RowID_Encabezado)
        {

            ListaEncabezado ObjEncabezado = new ListaEncabezado();
            int estado = db.Estado.Where(e => e.TipoEstado.Codigo == "TIPOLISTAPRECIO" && e.Nombre == "EnElaboracion").FirstOrDefault().RowID;
            ViewBag.ListaEstados = db.Estado.Where(f => f.TipoEstado.Codigo == "TIPOLISTAPRECIO");

            if (RowID_Encabezado == 0)
            {
                formulario = DeSerialize(formulario);
                ObjEncabezado.Nombre = formulario["nombre"];
                ObjEncabezado.TeatroID = int.Parse(formulario["teatro"]);
                ObjEncabezado.Descripcion = formulario["descripcion"];
                ObjEncabezado.FechaInicial = ModelosPropios.Util.HoraInsertar(formulario["fechainicialvigencia"]);
                ObjEncabezado.FechaFinal = ModelosPropios.Util.HoraInsertar(formulario["fechafinalvigencia"]);
                ObjEncabezado.CreadoPor = Session["usuario_creacion"].ToString();
                ObjEncabezado.EstadoID = int.Parse(formulario["Estado"]);
                ObjEncabezado.FechaCreacion = DateTime.Now;
                db.ListaEncabezado.Add(ObjEncabezado);
                db.SaveChanges();
            }
            else
            {
                ObjEncabezado = db.ListaEncabezado.Where(le => le.RowID == RowID_Encabezado).FirstOrDefault();
                formulario = DeSerialize(formulario);
                ObjEncabezado.Nombre = formulario["nombre"];
                ObjEncabezado.TeatroID = int.Parse(formulario["teatro"]);
                ObjEncabezado.Descripcion = formulario["descripcion"];
                ObjEncabezado.FechaInicial = ModelosPropios.Util.HoraInsertar(formulario["fechainicialvigencia"]);
                ObjEncabezado.FechaFinal = ModelosPropios.Util.HoraInsertar(formulario["fechafinalvigencia"]);
                ObjEncabezado.ModificadoPor = Session["usuario_creacion"].ToString();
                ObjEncabezado.EstadoID = int.Parse(formulario["Estado"]);
                ObjEncabezado.FechaModificacion = DateTime.Now;
                db.SaveChanges();

            }
            int codigo_encabezado = ObjEncabezado.RowID;
            //var dias = formulario["dias[]"].Split('|');
            //var nombre_detalle = formulario["nombre_detalle[]"].Split('|');
            //var servicios = formulario["servicio[]"].Split(',');
            //var precio_distribuidor = formulario["precio_distribuidor[]"].Split(',');
            //var precio = formulario["precio[]"].Split(',');
            //var formato = formulario["formato[]"].Split(',');
            //var hora_inicial = formulario["hora_inicial[]"].Split(',');
            //var hora_final = formulario["hora_final[]"].Split(',');
            //var fecha_inicial = formulario["fecha_inicial[]"].Split(',');
            //var fecha_final = formulario["fecha_final[]"].Split(',');
            //ListaDetalle ObjDetalle = new ListaDetalle();
            //for (int i = 0; i < nombre_detalle.Count(); i++)
            //{

            //    ObjDetalle.ListaEncabezadoID = codigo_encabezado;
            //    ObjDetalle.TeatroID = int.Parse(formulario["teatro"]);
            //    ObjDetalle.Nombre = nombre_detalle[i];
            //    ObjDetalle.Nombre = nombre_detalle[i];
            //    ObjDetalle.Nombre = nombre_detalle[i];
            //    ObjDetalle.Nombre = nombre_detalle[i];
            //    ObjDetalle.Nombre = nombre_detalle[i];
            //    ObjDetalle.Nombre = nombre_detalle[i];
            //    ObjDetalle.Nombre = nombre_detalle[i];
            //    ObjDetalle.Nombre = nombre_detalle[i];

            //    ObjDetalle.Nombre = nombre_detalle[i];
            //}
            return Json(codigo_encabezado, JsonRequestBehavior.AllowGet);
        }
        [CheckSessionOutAttribute]
        public JsonResult Guardar_Precio(FormCollection formulario, int RowID_Encabezado, int? RowID_Detalle)
        {
            string respuesta = "";
            string tipoAlert = "2";
            ListaDetalle ObjDetalle = new ListaDetalle();
            ListaEncabezado objencabezado = db.ListaEncabezado.Where(le => le.RowID == RowID_Encabezado).FirstOrDefault();
            int estado = int.Parse(db.Estado.Where(e => e.TipoEstado.Codigo == "TIPOLISTAPRECIO" && e.Nombre == "EnElaboracion").Select(s => s.RowID).First().ToString());
            // int.Parse(db.Estado.Where(e => e.TipoEstado.Codigo == "TIPOSALA" && e.Nombre == "EnFuncionamiento").Select(e => e.RowID).First().ToString());
            formulario = DeSerialize(formulario);
            if (RowID_Detalle != null)
            {
                ObjDetalle = db.ListaDetalle.Where(ld => ld.RowID == RowID_Detalle).FirstOrDefault();
                ObjDetalle.HoraInicial = Convertir_A_Hora_Militar(formulario["hora_inicial"]);
                ObjDetalle.HoraFinal = Convertir_A_Hora_Militar(formulario["hora_final"]);
                ObjDetalle.TipoListaDetalle = int.Parse(formulario["tipo_tarifa"]);
                ObjDetalle.ModificadoPor = Session["usuario_creacion"].ToString();
                ObjDetalle.FechaModificacion = DateTime.Now;
                respuesta = "Información actualizada exitosamente";
            }

            if (RowID_Detalle == null)
            {
                int RowID_Servicio = int.Parse(formulario["servicios"]);
                int RowID_Formato = int.Parse(formulario["formato"]);
                TimeSpan horainicial = Convertir_A_Hora_Militar(formulario["hora_inicial"]);
                TimeSpan horafinal = Convertir_A_Hora_Militar(formulario["hora_final"]);
                List<ListaDetalle> obj_detalle_valida = objencabezado.ListaDetalle.Where(ld => ld.TipoFormatoID == RowID_Formato && ld.TipoServicioID == RowID_Servicio && ld.ListaEncabezadoID == RowID_Encabezado).ToList();
                if (horainicial >= horafinal)
                {
                    respuesta = "La hora inicial no puede ser mayor a la final ";
                }
                else
                {
                    Boolean Insertar = true;
                    int validahorario = 0;
                    int validadias = 0;
                    int validatipotarifa = 0;
                    if (obj_detalle_valida.Count != 0)
                    {
                        foreach (CinemaPOS.Models.ListaDetalle item in obj_detalle_valida)
                        {
                            validahorario = 0;
                            validadias = 0;
                            if (item.HoraInicial.Value >= horainicial && item.HoraFinal.Value <= horainicial)
                            {

CinemaPOS/Views/Maestro/Ciudad.cshtml
@model CinemaPOS.Models.Ciudad

@{
    ViewBag.Title = "Ciudad";
    Layout = "~/Views/Inicio/Diseño.cshtml";
}

<script>
    function valida_formulario() {
        hasChangue = false;
        var validator = $("#formulario_ciudad").validate();
        if (validator.form()) {
            guardar_departamento();
        }
    }
</script>
<script>
    function guardar_departamento(encabezado) {
        if (!$("#formulario_ciudad").validate().form()) {
            return false;
        }
        if ($(".RowID_Encabezado").val() == 0) {
            $.ajax({
                type: "POST",
                url: "/Maestro/Guardar_Ciudad",
                data: {
                    RowID_Encabezado: $(".RowID_Encabezado").val(),
                    formulario: $("#formulario_ciudad").serialize(),
                },
                success: function (data) {
                    debugger;
                    if (data) {
                        swal("OK", "Creado...", "success");
                        window.location = "/Maestro/VistaCiudad"
                    } else {
                        swal("Advertencia", "Error al guardar...", "warning");
                    }
                },
                error: function () {
                    swal("Error al guardar la informacion de ciudad", "");
                }
            });
        }


        if ($(".RowID_Encabezado").val() != 0) {
            $.ajax({
                type: "POST",
                url: "/Maestro/Guardar_Ciudad",
                data: {
                    RowID_Encabezado: jQuery(".RowID_Encabezado").val(),
                    RowID_Detalle: jQuery(".RowID_Detalle").val(),
                    formulario: $("#formulario_ciudad").serialize(),
                },

                success: function (data) {
                    debugger;

                    if (data) {
                        swal("OK", "ACTUALIZADO...", "success");
                        window.location = "/Maestro/VistaCiudad"
                    } else {
                        sweetAlert("Advertencia", "ERROR ACTUALIZANDO", "warning");
                    }
                },
                error: function (data) {
                    sweetAlert("", data.respuesta, "warning");
                }

            });
        }
    }
</script>
<script src="~/Content/plugins/bootstrap-validator/bootstrapValidator.js"></script>



<!--Masked Input [ OPTIONAL ]-->

<script src="~/Content/plugins/masked-input/jquery.maskedinput.js"></script>

<!--Form validation [ SAMPLE ]-->
<script src="~/Content/js/demo/form-validation.js"></script>
<div>
    <p>
        <a class="btn btn-success" href='@Url.Action("VistaCiudad", "Maestro")'>Volver</a>
    </p>
</div>

<div class="panel">
    <div class="panel-heading">
        <h3 class="panel-title">Departamento</h3>
    </div>

    <form id="formulario_ciudad" data-toggle="validator" role="form">
        <input type="hidden" class="RowID_Encabezado" name="RowID_Encabezado" value="@Model.RowID" />
        <input type="hidden" class="RowID_Detalle" name="RowID_Detalle" />
        <div class="panel-body">
            <div class="row">
                <div class="col-sm-3">
                    <div class="form-group">
                        <label class="control-label">*País:</label>
                        <select name="pais" class="chosen form-control" required>
                            <option value="" disabled selected>Seleccione una opcion</option>
                            @foreach (CinemaPOS.Models.Pais pais in ViewBag.Pais)
                            {
                              <option value="@pais.RowID">@pais.Nombre</option>
                                
                            }
                        </select>
                    </div>
                </div>
                <div class="col-sm-3">
                    <div class="form-group">
                        <label class="control-label">*Departamento:</label>
                        <select name="departamento" class="chosen form-control" required>
                            <option value="" disabled selected>Seleccione una opcion</option>
                            @foreach (CinemaPOS.Models.Departamento departamento in ViewBag.Departamento)
                            {
                                if (@Model.DepartamentoID.Equals(@departamento.RowID))
                                {
                                    <option value="@departamento.RowID" selected>@departamento.Nombre</option>

                                }
                                else
                                {
                                    <option value="@departamento.RowID">@departamento.Nombre</option>


                                }

                            }
                        </select>
                    </div>
                </div>
                <div class="col-sm-3">
                    <div class="form-group">
                        <label class="control-label">*Nombre:</label>
                        <input name="nombre" id="nombre" class="form-control" value="@Model.Nombre" required>
                    </div>
                </div>
                <div class="col-sm-3">
                    <div class="form-group">
                        <label class="control-label">Descripción:</label>
                        <textarea name="descripcion" class="form-control" cols="20" rows="3" style="resize:none">@Model.Descripcion</textarea>
                    </div>
                </div>
            </div>
        </div>
        <div class="panel-footer text-right">
            @if (Model.RowID == 0)
            {
                <input class="btn btn-success" value="Guardar" onclick="javascript:valida_formulario()">
            }
            else
            {
                <input class="btn btn-success" value="Actualizar" onclick="javascript:valida_formulario()">
            }
        </div>
    </form>

</div>

CinemaPOS/Views/Maestro/Departamento.cshtml
@model CinemaPOS.Models.Departamento

@{
    ViewBag.Title = "Departamento";
    Layout = "~/Views/Inicio/Diseño.cshtml";}
<script>
    function valida_formulario() {
        hasChangue = false;
        var validator = $("#formulario_departamento").validate();
        if (validator.form()) {
            guardar_departamento();
        }
    }
</script>
<script>
    function guardar_departamento(encabezado) {
        if (!$("#formulario_departamento").validate().form()) {
            return false;
        }
        if ($(".RowID_Encabezado").val() == 0) {
            $.ajax({
                type: "POST",
                url: "/Maestro/Guardar_Departamento",
                data: {
                    RowID_Encabezado: $(".RowID_Encabezado").val(),
                    formulario: $("#formulario_departamento").serialize(),
                },
                success: function (data) {
                    debugger;
                    if (data) {
                        swal("OK", "Creado...", "success");
                        window.location = "/Maestro/VistaDepartamento"
                    } else {
                        swal("Advertencia", "Error al guardar...", "warning");
                    }
                },
                error: function () {
                    swal("Advertencia","Error al guardar la informacion de taquilla", "warning");
                }
            });
        }


        if ($(".RowID_Encabezado").val() != 0) {
            $.ajax({
                type: "POST",
                url: "/Maestro/Guardar_Departamento",
                data: {
                    RowID_Encabezado: jQuery(".RowID_Encabezado").val(),
                    RowID_Detalle: jQuery(".RowID_Detalle").val(),
                    formulario: $("#formulario_departamento").serialize(),
                },

                success: function (data) {
                    debugger;

                    if (data) {
                        swal("OK", "ACTUALIZADO...", "success");
                        window.location = "/Maestro/VistaDepartamento"
                    } else {
                        sweetAlert("Advertencia", "ERROR ACTUALIZANDO", "warning");
                    }
                },
                error: function (data) {
                    sweetAlert("", data.respuesta, "warning");
                }

            });
        }
    }
</script>







<script src="~/Content/plugins/bootstrap-validator/bootstrapValidator.js"></script>



<!--Masked Input [ OPTIONAL ]-->

<script src="~/Content/plugins/masked-input/jquery.maskedinput.js"></script>

<!--Form validation [ SAMPLE ]-->
<script src="~/Content/js/demo/form-validation.js"></script>
<div>
    <p>
        <a class="btn btn-success" href='@Url.Action("VistaDepartamento", "Maestro")'>Volver</a>
    </p>
</div>

<div class="panel">
    <div class="panel-heading">
        <h3 class="panel-title">Departamento</h3>
    </div>

    <form id="formulario_departamento" data-toggle="validator" role="form">
        <input type="hidden" class="RowID_Encabezado" name="RowID_Encabezado" value="@Model.RowID" />
        <input type="hidden" class="RowID_Detalle" name="RowID_Detalle" />
        <div class="panel-body">
            <div class="row">
                <div class="col-sm-3">
                    <div class="form-group">
                        <label class="control-label">*País:</label>
                        <select name="pais" class="chosen form-control" required>
                            <option value="" disabled selected>Seleccione una opcion</option>
                            @foreach (CinemaPOS.Models.Pais pais in ViewBag.Pais)
                            {
                                if (@Model.PaisID.Equals(@pais.RowID))
                                {
                                    <option value="@pais.RowID" selected>@pais.Nombre</option>
                                }
                                else
                                {
                                    <option value="@pais.RowID" >@pais.Nombre</option>
                                }
                            }
                        </select>
                    </div>
                </div>
                <div class="col-sm-3">
                    <div class="form-group">
                        <label class="control-label">*Nombre:</label>
                        <input name="nombre" id="nombre" class="form-control" value="@Model.Nombre" required>
                    </div>
                </div>
                <div class="col-sm-3">
                    <div class="form-group">
                        <label class="control-label">Descripción:</label>
                        <textarea name="descripcion" class="form-control" cols="20" rows="3" style="resize:none">@Model.Descripcion</textarea>
                    </div>
                </div>
            </div>
            </div>
            <div class="panel-footer text-right">
                @if (Model.RowID == 0)
                {
                    <input class="btn btn-success" value="Guardar" onclick="javascript:valida_formulario()">
                }
                else
                {
                    <input class="btn btn-success" value="Actualizar" onclick="javascript:valida_formulario()">
                }
            </div>
    </form>

</div>

CinemaPOS/Views/Maestro/VistaCiudad.cshtml
@model CinemaPOS.Models.Ciudad
@{
    ViewBag.Title = "VistaCiudad";
    Layout = "~/Views/Inicio/Diseño.cshtml";
}



<head>
    <!--jQuery [ REQUIRED ]-->
    <script src="~/Content/js/jquery-2.2.4.min.js"></script>
    <!--DataTables [ OPTIONAL ]-->
    <script src="~/Content/plugins/datatables/media/js/jquery.dataTables.js"></script>
    <script src="~/Content/plugins/datatables/media/js/dataTables.bootstrap.js"></script>
    <script src="~/Content/plugins/datatables/extensions/Responsive/js/dataTables.responsive.min.js"></script>
    <!--DataTables Sample [ SAMPLE ]-->
    <script src="~/Content/js/demo/tables-datatables.js"></script>
</head>
<p>
    <a class="btn btn-success" href='@Url.Action("Ciudad", "Maestro")'>+ Adicionar Ciudad</a>
</p>

<div class="panel">
    <div class="panel-heading">
        <h3 class="panel-title">Ciudades</h3>
    </div>
    <div class="panel-body">
        <table id="demo-dt-basic" class="table table-striped table-bordered table-funcion">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Nombre</th>
                    <th>Descripción</th>   
                    <th>Departamento</th>                 
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (CinemaPOS.Models.Ciudad lista_Ciudad in ViewBag.Ciudad)
                {
                    <tr>
                        <td>@lista_Ciudad.RowID</td>
                        <td>@lista_Ciudad.Nombre</td>
                        <td>@lista_Ciudad.Descripcion</td>
                        <td>@lista_Ciudad.Departamento.Nombre</td>                    
                        <td><a href="@Url.Action("Ciudad", "Maestro", new { RowID_Lista = lista_Ciudad.RowID })"><i class="glyphicon glyphicon-pencil"></i></a></td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>