CinemaPOS/Models/Pqrs.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaPOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pqrs
    {
        public Pqrs()
        {
            this.EvidenciaPqrs = new HashSet<EvidenciaPqrs>();
            this.Seguimiento = new HashSet<Seguimiento>();
        }
    
        public int RowID { get; set; }
        public Nullable<int> TeatroID { get; set; }
        public Nullable<int> TipoSolicitudID { get; set; }
        public Nullable<int> TerceroID { get; set; }
        public Nullable<int> EstadoID { get; set; }
        public string Titulo { get; set; }
        public string Descripcion { get; set; }
        public Nullable<System.DateTime> FechaSuceso { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string CreadoPor { get; set; }
    
        public virtual Estado Estado { get; set; }
        public virtual Teatro Teatro { get; set; }
        public virtual Tercero Tercero { get; set; }
        public virtual ICollection<EvidenciaPqrs> EvidenciaPqrs { get; set; }
        public virtual TipoSolicitud TipoSolicitud { get; set; }
        public virtual ICollection<Seguimiento> Seguimiento { get; set; }
    }
}

CinemaPOS/Models/Seguimiento.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaPOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seguimiento
    {
        public Seguimiento()
        {
            this.SeguientoEvidencia = new HashSet<SeguientoEvidencia>();
        }
    
        public int RowID { get; set; }
        public Nullable<int> AreaAnteriorID { get; set; }
        public Nullable<int> AreaActualID { get; set; }
        public Nullable<int> EstadoID { get; set; }
        public string Observaciones { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public Nullable<System.DateTime> CreadoPor { get; set; }
        public Nullable<int> PQRS_ID { get; set; }
    
        public virtual Estado Estado { get; set; }
        public virtual Opcion Opcion { get; set; }
        public virtual Opcion Opcion1 { get; set; }
        public virtual Pqrs Pqrs { get; set; }
        public virtual ICollection<SeguientoEvidencia> SeguientoEvidencia { get; set; }
    }
}

CinemaPOS/Controllers/PQRSController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CinemaPOS.Models;

namespace CinemaPOS.Controllers.Inicio
{
    public class PQRSController : Controller
    {
        //
        // GET: /PQRS/
    CinemaPOSEntities db = new CinemaPOSEntities();
        private FormCollection DeSerialize(FormCollection formulario)
        {
            FormCollection collection = new FormCollection();
            //un-encode, and add spaces back in
            string querystring = Uri.UnescapeDataString(formulario["formulario"]).Replace("+", " ");
            var split = querystring.Split(new[] { '&' }, StringSplitOptions.RemoveEmptyEntries);
            Dictionary<string, string> items = new Dictionary<string, string>();
            foreach (string s in split)
            {
                string text = s.Substring(0, s.IndexOf("="));
                string value = s.Substring(s.IndexOf("=") + 1);

                if (items.Keys.Contains(text))
                    items[text] = items[text] + "," + value;
                else
                    items.Add(text, value);
            }
            foreach (var i in items)
            {
                collection.Add(i.Key, i.Value);
            }
            return collection;
        }
        public ActionResult CreacionPQRS(int? RowID_pqrs,int? RowIdTercero)
        {
           
            //ViewBag.TipoTerceroID = new List<Opcion>();
            ViewBag.TipoTerceroID = db.Opcion.Where(f => f.Tipo.Codigo == "TIPOTERCERO").ToList();
            ViewBag.SexoID = db.Opcion.Where(f => f.Tipo.Codigo == "TIPOSEXO").ToList();
            ViewBag.CiudadID = db.Ciudad.ToList().OrderBy(f => f.Nombre);
            ViewBag.TipoIdentificacion = db.Opcion.Where(f => f.Tipo.Codigo == "TIPOIDENTIFICACION").ToList();
            
            if (RowID_pqrs==null|| RowID_pqrs==0)
            {
               
                return View(new ModelosPropios.Model.Modelos_Pqrs());
            }
            else
            {
                ModelosPropios.Model.Modelos_Pqrs ObjModelos = new ModelosPropios.Model.Modelos_Pqrs();
                return View(db.Pqrs.Where(p=>p.RowID==RowID_pqrs).FirstOrDefault());
            }
        }
        public ActionResult ModalTercero()
        {
            
            ViewBag.Teatros = db.Teatro.ToList();
            ViewBag.TipoPQRS = db.TipoSolicitud.Where(ts => ts.Estado == true).ToList();
            return View();
        }
        public JsonResult Guardar_PQRS(FormCollection formulario,int? RowIDTercero)
        {
            Pqrs Obj_pqrs = new Pqrs();
            
            formulario = DeSerialize(formulario);
            Obj_pqrs.TeatroID = int.Parse(formulario["teatro"]);
            Obj_pqrs.TipoSolicitudID = int.Parse(formulario["tiposolicitud"]);
            Obj_pqrs.TerceroID = RowIDTercero;
            Obj_pqrs.EstadoID = db.Estado.Where(e => e.TipoEstado.Codigo == "TIPOPQRS" && e.Nombre == "Recibida").FirstOrDefault().RowID;
            Obj_pqrs.Titulo = formulario["Titulo"];
            Obj_pqrs.Descripcion = formulario["descripcion-pqrs"];
            Obj_pqrs.FechaSuceso = ModelosPropios.Util.HoraInsertar( formulario["fecha_suceso"]);
            Obj_pqrs.FechaCreacion = DateTime.Now;
            Obj_pqrs.CreadoPor = Session["usuario_creacion"].ToString();
            db.Pqrs.Add(Obj_pqrs);
            db.SaveChanges();
            return Json(new { respuesta="Creado Exitosamente"});
        }
        public JsonResult CargarCLiente()
        {
            string term = Request.Params["term"];
            try
            {
                var data = (from Sucur in db.Tercero
                                                 .Where(f => f.Nombre.Contains(term)||f.Identificacion.Contains(term.Trim())).ToList()
                            select new
                            {
                                rowid = Sucur.RowID,
                                nombre = Sucur.Nombre,
                                label = Sucur.Nombre + " " + Sucur.Apellidos


                            }).Distinct().OrderBy(f => f.label).Take(15);
                //data = data.Where(f => f.label.Contains(term));
                return Json(data, JsonRequestBehavior.AllowGet);
            }
            catch (Exception e)
            {
                return Json(null, JsonRequestBehavior.AllowGet);
            }

        }

        public ActionResult VistaPQRS()
        {
            return View(db.Pqrs.ToList());
        }
        public ActionResult Seguimiento(int? Rowid_Pqrs)
        {
            return View(db.Pqrs.Where(s=>s.RowID==Rowid_Pqrs).FirstOrDefault());
        }
    }
}

CinemaPOS/Views/PQRS/ModalTercero.cshtml
@{
    ViewBag.Title = "ModalTercero";
    Layout = null;
}
<script>
    $("#myModal").modal('show');
    //alert();
    function guaradar_pqrs() {
        var validator = $("#formulario_tercero").validate();
        if (validator.form()) {
            $.ajax({
                type: "POST",
                url: "/PQRS/Guardar_PQRS",
                data: {
                    RowIDTercero:@(Request.Params["rowid_tercero"]),
                    formulario: $("#formpqrs").serialize()
                },
                success:function(){
                    swal("","Información guardada exitosamente");
                }
            })
        }
        
    }
</script>
<div class="modal fade" id="myModal" role="dialog">
    <div class="modal-dialog">
        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Creacion PQRS</h4>
            </div>
            <div class="modal-body">
                <div id="divpqrs">
                    <form id="formpqrs">
                        <div class="row">
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <label class="control-label">Teatro</label>
                                    <select class="form-control" name="teatro" required>
                                        <option></option>
                                        @foreach (CinemaPOS.Models.Teatro teatro in ViewBag.Teatros)
                                        {
                                            <option value="@teatro.RowID">@teatro.Nombre</option>
                                        }
                                    </select>
                                </div>
                            </div>
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <label class="control-label">Tipo solicitud</label>
                                    <select class="form-control" name="tiposolicitud" required>
                                        <option></option>
                                        @foreach (CinemaPOS.Models.TipoSolicitud solicitud in ViewBag.TipoPQRS)
                                        {
                                            <option value="@solicitud.RowID">@solicitud.Nombre</option>
                                        }
                                    </select>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <label class="control-label">Titulo PQRS</label>
                                    <input type="text" class="form-control" name="Titulo" required />
                                </div>
                            </div>
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <label class="control-label">Fecha suceso</label>
                                    <input type="text" class="form-control" name="fecha_suceso" id="fecha_suceso" required />
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-sm-12">
                                <div class="form-group">
                                    <label class="control-label">Descripcion del suceso</label>
                                    <textarea name="descripcion-pqrs" class="form-control" cols="2" rows="12" required></textarea>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" onclick="guaradar_pqrs()">Guardar PQRS</button>
            </div>
        </div>
    </div>

</div>

CinemaPOS/Views/PQRS/Seguimiento.cshtml
@model  CinemaPOS.Models.Pqrs

@{
    ViewBag.Title = "Seguimiento";
    Layout = "~/Views/Inicio/Diseño.cshtml";
}
<div class="panel">
    <div class="panel-heading">
        <h3 class="panel-title">Seguimiento PQRS</h3>
    </div>vb
    <div class="panel-body">
        <div class="col-lg-4">
            <div class="panel-body text-center">
                @if (Model.Seguimiento.Count() != 0)
                {
                    <p class="text-muted">Administrator</p>
                    <p class="text-sm">Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. </p>
                    <button class="btn btn-primary mar-ver"><i class="demo-pli-male icon-fw"></i>Follow</button>
                    <ul class="list-unstyled text-center bord-top pad-top mar-no row">
                        <li class="col-xs-4">
                            <span class="text-lg text-semibold text-main">1,345</span>
                            <p class="text-muted mar-no">Fecha suceso</p>
                        </li>
                        <li class="col-xs-4">
                            <span class="text-lg text-semibold text-main">23K</span>
                            <p class="text-muted mar-no">Fecha Creación</p>
                        </li>
                        <li class="col-xs-4">
                            <span class="text-lg text-semibold text-main">278</span>
                            <p class="text-muted mar-no">Creado por</p>
                        </li>
                    </ul>
                }
                
            </div>
        </div>
        <div class="panel">
            <div class="panel-heading">
                <h3 class="panel-title">Informacion de la PQRS</h3>
            </div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-sm-6">
                        <div class="panel">
                            <div class="panel-heading">
                                <h3 class="panel-title">Datos del cliente</h3>
                            </div>
                            <div class="panel-body">
                                <div class="row">
                                    <div class="col-lg-6">
                                        <label class="control-label">Nombre:  @Model.Tercero.Nombre</label> 
                                    </div>
                                    <div class="col-lg-6">
                                        <label class="control-label">Identificacion:  @Model.Tercero.Identificacion</label>
                                    </div>
                                    <div class="row">
                                        <div class="col-lg-6">
                                            <label class="control-label">Telefono:  @Model.Tercero.Telefono</label>
                                        </div>
                                        <div class="col-lg-6">
                                            <label class="control-label">Ciudad:  @Model.Tercero.Ciudad.Nombre</label>
                                        </div>
                   
                                    <div class="row">
                                        <div class="col-lg-6">
                                            <label class="control-label">Correo:  @Model.Tercero.Correo</label>
                                        </div>
                                        <div class="col-lg-6">
                                            <label class="control-label">Fecha de nacimiento:  @Model.Tercero.FechaNacimiento.Value.ToString("dd/MM/yyyy")</label>
                                        </div>
                                    </div>
                                </div>
                                
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-6">
                        <div class="panel">
                            <div class="panel-heading">
                                <h3 class="panel-title">Informacion de la PQRS</h3>
                            </div>
                            <div class="panel-body">
                                <div class="row">
                                    <div class="col-sm-6">
                                        <label class="control-label">Titulo:  @Model.Titulo</label>
                                    </div>
                                    <div class="col-sm-6">
                                        <label class="control-label">Teatro:  @Model.Teatro.Nombre</label>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-sm-6">
                                        <label class="control-label">Tipo solicitud:  @Model.TipoSolicitud.Nombre</label>
                                    </div>
                                    <div class="col-sm-6">
                                        <label class="control-label">Estado:  @Model.Estado.Nombre</label>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-sm-6">
                                        <label class="control-label">Fecha creación:  @Model.FechaCreacion.Value.ToString("dd/MM/yyyy")</label>
                                    </div>
                                    <div class="col-sm-6">
                                        <label class="control-label">Fecha del suceso:  @Model.FechaSuceso.Value.ToString("dd/MM/yyyy")</label>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-sm-12">
                                        <p class="control-label">Descripción de la PQRS <br />@Model.Descripcion</p>
                                    </div>
                                </div>
                                
                            </div>
                        </div>
                        
                    </div>
                </div>
            </div>
        </div>
        

    </div>
</div>

CinemaPOS/Views/PQRS/VistaPQRS.cshtml
@model IEnumerable<CinemaPOS.Models.Pqrs>

@{
    ViewBag.Title = "Vista PQRS";
    Layout = "~/Views/Inicio/Diseño.cshtml";
}
<p>
    <a class="btn btn-success" href='@Url.Action("Pelicula", "Pelicula")'>Nueva PQRS</a>
</p>
<div class="panel">
    <div class="panel-heading">
        <h3 class="panel-title">Lista PQRS</h3>
    </div>
    <div class="panel-body">
        <table id="demo-dt-basic" class="table table-striped table-bordered" cellspacing="0" width="100%">
            <thead>
                <tr>
                    <th>Titulo PQRS</th>
                    <th>Teatro</th>
                    <th class="min-tablet">Tipo solicitud</th>
                    <th class="min-desktop">Estado PQRS</th>
                    <th>Fecha suceso</th>
                    <th>Fecha creación</th>
                    <th>Creado por</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (CinemaPOS.Models.Pqrs pqrs in Model.ToList())
                {
                    <tr>
                        <td>@pqrs.Titulo</td>
                        <td>@pqrs.Teatro.Nombre</td>
                        <td>@pqrs.TipoSolicitud.Nombre</td>
                        <td>@pqrs.Estado.Nombre</td>
                        <td>@pqrs.FechaSuceso.Value.ToString("dd/MM/yyyy")</td>
                        <td>@pqrs.FechaCreacion.Value.ToString("dd/MM/yyyy")</td>
                        <td>@pqrs.CreadoPor</td>
                        <td><a href="@Url.Action("Seguimiento","PQRS",new { Rowid_Pqrs=pqrs.RowID})"><i class="ion-filing"></i></a></td>
                    </tr>
                }

            </tbody>
        </table>
    </div>
</div>